#!/usr/bin/env python3
"""Fail-closed checks and synthetic smoke helpers for the LeRobot ACT isolate."""

from __future__ import annotations

import argparse
import hashlib
import contextlib
import json
import math
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Mapping


LEROBOT_COMMIT = "7e241bd630a3719a56157a497ce5d08f244784f1"
REQUIRED_ANCHORS = (
    "lerobot[training] @ git+https://github.com/huggingface/lerobot.git@"
    + LEROBOT_COMMIT,
    "torch==2.11.0+cu128",
    "torchvision==0.26.0+cu128",
    "numpy==2.2.6",
    "h5py==3.16.0",
    "mujoco==3.11.0",
    "imageio==2.37.4",
    "safetensors==0.8.0",
)
CUDA_LADDER = ((4, 1), (2, 2), (1, 4))
COMPATIBILITY_FAILURE_ALLOWLIST = frozenset(
    {
        "act_api_incompatible",
        "cuda_kernel_incompatible",
        "cuda_oom_batch1",
        "lock_resolution_incompatible",
        "non_finite",
        "platform_wheel_incompatible",
        "save_load_mismatch",
    }
)


class ContractError(RuntimeError):
    """Raised when an immutable adoption input violates the frozen contract."""


class CompatibilityFailure(RuntimeError):
    """A deterministic, allowlisted incompatibility with complete evidence."""

    def __init__(self, failure_class: str, message: str) -> None:
        super().__init__(message)
        self.failure_class = failure_class


def read_requirement_anchors(path: Path) -> tuple[str, ...]:
    """Return the exact package anchors and reject launcher requirements."""

    lines = tuple(
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )
    if lines != REQUIRED_ANCHORS:
        raise ContractError(
            "requirements.lerobot-act.in must contain only the frozen package anchors"
        )
    return lines


def build_isolate_environment(
    repository: Path,
    inherited: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Build the only environment permitted to launch the LeRobot isolate."""

    root = repository.resolve()
    environment = dict(os.environ if inherited is None else inherited)
    environment.pop("VIRTUAL_ENV", None)
    environment.pop("PYTHONPATH", None)
    environment.update(
        {
            "EMB": str(root),
            "PATH": f"{root}/.venv-lerobot/bin:/usr/local/bin:/usr/bin:/bin",
            "PYTHONPATH": f"{root}/src",
            "UV_CACHE_DIR": f"{root}/cache/uv-lerobot",
            "PIP_CACHE_DIR": f"{root}/cache/pip-lerobot",
            "TMPDIR": f"{root}/cache/tmp-lerobot",
            "XDG_CACHE_HOME": f"{root}/cache/xdg-lerobot",
            "HF_HOME": f"{root}/hf",
            "TORCH_HOME": f"{root}/cache/torch",
            "CUDA_CACHE_PATH": f"{root}/cache/cuda-lerobot",
            "CCACHE_DIR": f"{root}/cache/ccache-lerobot",
            "PYTHONPYCACHEPREFIX": f"{root}/cache/pycache-lerobot",
            "PYTHONDONTWRITEBYTECODE": "1",
            "UV_PYTHON_DOWNLOADS": "never",
            "PYTHONHASHSEED": "0",
            "CUBLAS_WORKSPACE_CONFIG": ":4096:8",
            "MUJOCO_GL": "egl",
        }
    )
    return environment


def resource_blocker(
    phase: str,
    data_free_kib: int,
    root_free_kib: int,
) -> str | None:
    """Return the frozen disk-space blocker for a bootstrap phase, if any."""

    valid_phases = {"initial", "post-create", "post-sync", "post-smoke"}
    if phase not in valid_phases:
        raise ContractError(f"unknown resource phase: {phase}")
    data_minimum_gib = 20 if phase == "initial" else 15
    if data_free_kib < data_minimum_gib * 1024**2:
        return "insufficient_data_space"
    if root_free_kib < 3 * 1024**2:
        return "insufficient_root_space"
    return None


def validate_compiled_lock(path: Path) -> dict[str, object]:
    """Validate the resolver-produced, hash-locked cu128 requirements file."""

    text = path.read_text(encoding="utf-8")
    if "# This file was autogenerated by uv" not in text:
        raise ContractError("LeRobot lock must be generated by uv pip compile")
    if "--index-url https://pypi.org/simple" not in text:
        raise ContractError("LeRobot lock must record the public package index")

    start_pattern = re.compile(
        r"^(?P<name>[A-Za-z0-9][A-Za-z0-9_.-]*)(?:==(?P<version>[^ ;\\]+)| @ (?P<url>\S+))",
        re.MULTILINE,
    )
    starts = list(start_pattern.finditer(text))
    if not starts:
        raise ContractError("LeRobot lock contains no resolved packages")

    packages: dict[str, dict[str, object]] = {}
    for index, match in enumerate(starts):
        name = match.group("name").lower().replace("_", "-")
        if name in packages:
            raise ContractError(f"duplicate locked package: {name}")
        block_end = starts[index + 1].start() if index + 1 < len(starts) else len(text)
        block = text[match.start() : block_end]
        version = match.group("version")
        url = match.group("url")
        hashes = re.findall(r"--hash=sha256:([0-9a-f]{64})(?:\s|$)", block)
        if version is not None and not hashes:
            raise ContractError(f"locked registry package has no SHA-256 hash: {name}")
        if version is None and not url:
            raise ContractError(f"unversioned locked package: {name}")
        packages[name] = {
            "version": version,
            "url": url,
            "hashes": hashes,
            "block": block,
        }

    lerobot = packages.get("lerobot")
    expected_lerobot_url = (
        "git+https://github.com/huggingface/lerobot.git@" + LEROBOT_COMMIT
    )
    if lerobot is None or lerobot["url"] != expected_lerobot_url:
        raise ContractError("LeRobot lock does not pin the approved upstream commit")

    key_versions = {
        "h5py": "3.16.0",
        "imageio": "2.37.4",
        "mujoco": "3.11.0",
        "numpy": "2.2.6",
        "safetensors": "0.8.0",
        "torch": "2.11.0+cu128",
        "torchvision": "0.26.0+cu128",
    }
    for name, expected_version in key_versions.items():
        if packages.get(name, {}).get("version") != expected_version:
            raise ContractError(f"wrong locked version for {name}")
    cu128_source = "# from https://download.pytorch.org/whl/cu128"
    for name in ("torch", "torchvision"):
        if cu128_source not in str(packages[name]["block"]):
            raise ContractError(f"{name} is not locked to the official cu128 index")

    return {
        "package_count": len(packages),
        "key_requirements": key_versions,
        "lerobot_commit": LEROBOT_COMMIT,
        "all_registry_requirements_hashed": all(
            package["hashes"]
            for package in packages.values()
            if package["version"] is not None
        ),
    }


def known_dependency_security_gate(path: Path) -> dict[str, object]:
    """Block environment creation for vulnerabilities confirmed by OSV evidence."""

    validate_compiled_lock(path)
    text = path.read_text(encoding="utf-8")
    versions = {
        name: match.group(1)
        for name in ("datasets", "setuptools", "torch")
        if (
            match := re.search(
                rf"^{re.escape(name)}==([^ ;\\]+)", text, flags=re.MULTILINE
            )
        )
    }
    policies = (
        ("datasets", "5.0.1", ["PYSEC-2026-3716"]),
        (
            "setuptools",
            "83.0.0",
            ["GHSA-h35f-9h28-mq5c", "PYSEC-2026-3447"],
        ),
        ("torch", "2.13.0", ["GHSA-rrmf-rvhw-rf47"]),
    )

    def release_tuple(version: str) -> tuple[int, int, int]:
        numeric = version.split("+", 1)[0]
        parts = numeric.split(".")
        if len(parts) < 3 or not all(part.isdigit() for part in parts[:3]):
            raise ContractError(f"unsupported locked version for security gate: {version}")
        return tuple(int(part) for part in parts[:3])  # type: ignore[return-value]

    issues = []
    for package, safe_floor, advisories in policies:
        installed = versions.get(package)
        if installed is None:
            raise ContractError(f"security-gated package missing from lock: {package}")
        if release_tuple(installed) < release_tuple(safe_floor):
            issues.append(
                {
                    "package": package,
                    "installed": installed,
                    "safe_floor": safe_floor,
                    "advisories": advisories,
                }
            )
    if issues:
        return {
            "status": "blocked",
            "passed": None,
            "reason_code": "dependency_security",
            "issues": issues,
            "environment_creation_allowed": False,
            "smoke_allowed": False,
        }
    return {
        "status": "passed",
        "passed": True,
        "issues": [],
        "environment_creation_allowed": True,
        "smoke_allowed": True,
    }


def _validate_source_manifest_shape(manifest: Mapping[str, object]) -> None:
    required_fields = {
        "schema_version",
        "manifest_id",
        "git_commit",
        "head_tree",
        "scope_config_sha256",
        "path_set_sha256",
        "index_entries_sha256",
        "content_entries_sha256",
        "tracked_status_sha256",
        "source_provenance_clean",
        "entries",
    }
    missing = required_fields.difference(manifest)
    if missing:
        raise ContractError(
            "source manifest is missing required fields: " + ", ".join(sorted(missing))
        )
    if manifest["schema_version"] != "lerobot-source-input-manifest.v1":
        raise ContractError("unsupported source manifest schema")
    if not re.fullmatch(r"sha256:[0-9a-f]{64}", str(manifest["manifest_id"])):
        raise ContractError("invalid source manifest identity")
    if not re.fullmatch(r"[0-9a-f]{40,64}", str(manifest["git_commit"])):
        raise ContractError("invalid source commit")
    if not isinstance(manifest["source_provenance_clean"], bool):
        raise ContractError("source_provenance_clean must be boolean")
    entries = manifest["entries"]
    if not isinstance(entries, list) or not entries:
        raise ContractError("source manifest entries must be a nonempty list")
    paths = [entry.get("path") for entry in entries if isinstance(entry, dict)]
    if len(paths) != len(entries) or paths != sorted(set(paths)):
        raise ContractError("source manifest entries must have sorted unique paths")


def source_lineage_gate(
    start_manifest: Mapping[str, object],
    current_manifest: Mapping[str, object],
) -> dict[str, object]:
    """Require exact start/current source lineage before a terminal receipt."""

    _validate_source_manifest_shape(start_manifest)
    _validate_source_manifest_shape(current_manifest)
    if start_manifest != current_manifest:
        return {
            "formal_ready": False,
            "non_acceptance": True,
            "blocker": "source_input_manifest_drift",
        }
    if start_manifest["source_provenance_clean"] is not True:
        return {
            "formal_ready": False,
            "non_acceptance": True,
            "blocker": "source_provenance_not_clean",
        }
    return {
        "formal_ready": True,
        "non_acceptance": False,
        "source_input_manifest_id": start_manifest["manifest_id"],
        "source_commit": start_manifest["git_commit"],
    }


def terminal_decision(
    *,
    requested_status: str,
    failure_class: str | None,
    evidence_complete: bool,
    resource_blocker_code: str | None,
    source_lineage: Mapping[str, object],
) -> dict[str, object]:
    """Apply fail-closed admission rules to a smoke runner's requested state."""

    if resource_blocker_code is not None:
        return {
            "status": "blocked",
            "passed": None,
            "reason_code": resource_blocker_code,
            "non_acceptance": True,
        }
    if not evidence_complete:
        return {
            "status": "blocked",
            "passed": None,
            "reason_code": "incomplete_evidence",
            "non_acceptance": True,
        }
    if source_lineage.get("formal_ready") is not True:
        return {
            "status": "blocked",
            "passed": None,
            "reason_code": str(source_lineage.get("blocker", "source_lineage_invalid")),
            "non_acceptance": True,
        }
    if requested_status == "passed":
        return {
            "status": "passed",
            "passed": True,
            "non_acceptance": False,
        }
    if (
        requested_status == "failed"
        and failure_class in COMPATIBILITY_FAILURE_ALLOWLIST
    ):
        return {
            "status": "failed",
            "passed": False,
            "failure_class": failure_class,
            "non_acceptance": False,
        }
    return {
        "status": "blocked",
        "passed": None,
        "reason_code": "unknown_failure",
        "non_acceptance": True,
    }


def act_config_spec(*, device: str) -> dict[str, object]:
    """Return the exact R1.4 ACTConfig values as dependency-free data."""

    if device not in {"cpu", "cuda"}:
        raise ContractError(f"unsupported smoke device: {device}")
    return {
        "input_features": {
            "observation.images.front": {"type": "VISUAL", "shape": (3, 128, 128)},
            "observation.images.wrist": {"type": "VISUAL", "shape": (3, 128, 128)},
            "observation.state": {"type": "STATE", "shape": (8,)},
        },
        "output_features": {"action": {"type": "ACTION", "shape": (8,)}},
        "n_obs_steps": 1,
        "chunk_size": 16,
        "n_action_steps": 1,
        "vision_backbone": "resnet18",
        "pretrained_backbone_weights": "ResNet18_Weights.IMAGENET1K_V1",
        "dim_model": 512,
        "n_heads": 8,
        "dim_feedforward": 3200,
        "n_encoder_layers": 4,
        "n_decoder_layers": 1,
        "use_vae": True,
        "latent_dim": 32,
        "n_vae_encoder_layers": 4,
        "dropout": 0.1,
        "kl_weight": 10.0,
        "temporal_ensemble_coeff": None,
        "optimizer_lr": 1e-5,
        "optimizer_lr_backbone": 1e-5,
        "optimizer_weight_decay": 1e-4,
        "normalization_mapping": {
            "VISUAL": "IDENTITY",
            "STATE": "IDENTITY",
            "ACTION": "IDENTITY",
        },
        "device": device,
        "use_amp": device == "cuda",
        "push_to_hub": False,
    }


def make_synthetic_batch(torch_module, *, batch_size: int, device: str):
    """Create the fixed synthetic batch without reading M2 or any training artifact."""

    if batch_size < 1:
        raise ContractError("synthetic batch size must be positive")
    generator = torch_module.Generator(device="cpu")
    generator.manual_seed(0)
    tensors = {
        "observation.images.front": torch_module.rand(
            batch_size, 3, 128, 128, generator=generator, dtype=torch_module.float32
        ),
        "observation.images.wrist": torch_module.rand(
            batch_size, 3, 128, 128, generator=generator, dtype=torch_module.float32
        ),
        "observation.state": torch_module.rand(
            batch_size, 8, generator=generator, dtype=torch_module.float32
        ),
        "action": torch_module.rand(
            batch_size, 16, 8, generator=generator, dtype=torch_module.float32
        ),
        "action_is_pad": torch_module.zeros(
            batch_size, 16, dtype=torch_module.bool
        ),
    }
    return {key: value.to(device) for key, value in tensors.items()}


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _evidence_entries(repository: Path, paths: list[Path]) -> list[dict[str, object]]:
    """Describe regular evidence files without allowing paths outside the repo."""

    root = repository.resolve()
    entries = []
    for path in paths:
        resolved = path.resolve()
        try:
            relative = resolved.relative_to(root).as_posix()
        except ValueError as exc:
            raise ContractError("supporting evidence is outside the repository") from exc
        if path.is_symlink() or not resolved.is_file():
            raise ContractError(f"supporting evidence is not a regular file: {relative}")
        entries.append(
            {
                "path": relative,
                "sha256": sha256_file(resolved),
                "size_bytes": resolved.stat().st_size,
            }
        )
    entries.sort(key=lambda item: str(item["path"]))
    return entries


def verify_runtime_identity(
    *,
    repository: Path,
    expected_prefix: Path,
    executable: Path,
    sys_prefix: Path,
    python_version: tuple[int, int, int],
    environment: Mapping[str, str],
    module_paths: Mapping[str, Path],
) -> dict[str, object]:
    """Prove that Python and every adoption dependency come from one prefix."""

    root = repository.resolve()
    prefix = expected_prefix.resolve()
    expected_executable = (prefix / "bin" / "python").resolve()
    actual_executable = executable.resolve()
    if actual_executable != expected_executable:
        raise ContractError("runtime executable is outside the unique LeRobot prefix")
    if sys_prefix.resolve() != prefix:
        raise ContractError("runtime sys.prefix is not the unique LeRobot prefix")
    if python_version[:2] != (3, 12):
        raise ContractError("LeRobot launcher requires Python 3.12")
    if "VIRTUAL_ENV" in environment:
        raise ContractError("VIRTUAL_ENV must be unset for the LeRobot isolate")
    if environment.get("PYTHONPATH") != str(root / "src"):
        raise ContractError("PYTHONPATH must contain only the repository src directory")
    expected_path = f"{prefix}/bin:/usr/local/bin:/usr/bin:/bin"
    if environment.get("PATH") != expected_path:
        raise ContractError("PATH does not select the unique LeRobot prefix")
    for name, module_path in sorted(module_paths.items()):
        try:
            module_path.resolve().relative_to(prefix)
        except ValueError as exc:
            raise ContractError(f"{name} module path is outside the LeRobot prefix") from exc

    return {
        "python_version": ".".join(str(part) for part in python_version),
        "prefix": str(prefix),
        "executable": str(actual_executable),
        "executable_sha256": "sha256:" + sha256_file(actual_executable),
        "module_paths": {
            name: str(module_path.resolve()) for name, module_path in sorted(module_paths.items())
        },
    }


def exercise_policy(
    torch_module,
    *,
    policy,
    optimizer,
    batch: Mapping[str, object],
    device: str,
    accumulation_steps: int,
) -> dict[str, object]:
    """Run the complete train and direct chunk-prediction adoption chain."""

    if accumulation_steps < 1:
        raise ContractError("gradient accumulation steps must be positive")

    def autocast_context():
        if device == "cuda":
            return torch_module.autocast(device_type="cuda", dtype=torch_module.bfloat16)
        return contextlib.nullcontext()

    policy.train()
    optimizer.zero_grad(set_to_none=True)
    observed_loss = None
    observed_loss_dict = None
    for _ in range(accumulation_steps):
        with autocast_context():
            loss, loss_dict = policy.forward(batch)
        if loss.ndim != 0 or not bool(torch_module.isfinite(loss).item()):
            raise CompatibilityFailure("non_finite", "ACT loss is not a finite scalar")
        loss_values = [
            float(value.detach().cpu()) if hasattr(value, "detach") else float(value)
            for value in loss_dict.values()
        ]
        if not all(math.isfinite(value) for value in loss_values):
            raise CompatibilityFailure("non_finite", "ACT loss_dict contains non-finite values")
        (loss / accumulation_steps).backward()
        observed_loss = float(loss.detach().cpu())
        observed_loss_dict = dict(zip(loss_dict, loss_values, strict=True))

    gradients = [parameter.grad for parameter in policy.parameters() if parameter.grad is not None]
    if not gradients or not all(
        bool(torch_module.isfinite(gradient).all().item()) for gradient in gradients
    ):
        raise CompatibilityFailure("non_finite", "ACT gradients are missing or non-finite")
    optimizer.step()

    policy.eval()
    with torch_module.no_grad(), autocast_context():
        prediction = policy.predict_action_chunk(batch)
    expected_shape = (batch["observation.state"].shape[0], 16, 8)
    if tuple(prediction.shape) != expected_shape:
        raise CompatibilityFailure(
            "act_api_incompatible",
            f"ACT prediction shape {tuple(prediction.shape)} != {expected_shape}",
        )
    if not bool(torch_module.isfinite(prediction).all().item()):
        raise CompatibilityFailure("non_finite", "ACT prediction contains non-finite values")

    return {
        "loss": observed_loss,
        "loss_dict": observed_loss_dict,
        "loss_finite": True,
        "loss_dict_finite": True,
        "gradients_finite": True,
        "optimizer_step_completed": True,
        "prediction_shape": list(prediction.shape),
        "prediction_finite": True,
    }


def audit_dependency_lock(
    *, requirements: Path, lock: Path, output: Path
) -> dict[str, object]:
    """Publish non-terminal evidence explaining why this isolate is disabled."""

    read_requirement_anchors(requirements)
    lock_summary = validate_compiled_lock(lock)
    decision = known_dependency_security_gate(lock)
    payload = {
        "schema_version": "lerobot-dependency-security-evidence.v1",
        "status": decision["status"],
        "passed": decision["passed"],
        "reason_code": decision.get("reason_code"),
        "lock_classification": "development-blocked",
        "environment_creation_allowed": decision["environment_creation_allowed"],
        "smoke_allowed": decision["smoke_allowed"],
        "issues": decision["issues"],
        "lerobot_commit": LEROBOT_COMMIT,
        "requirements_sha256": sha256_file(requirements),
        "lock_sha256": sha256_file(lock),
        "package_count": lock_summary["package_count"],
        "key_requirements": lock_summary["key_requirements"],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.write("\n")
    return payload


def build_dependency_blocked_receipt(
    *,
    repository: Path,
    expected_prefix: Path,
    dependency_evidence: Path,
    supporting_evidence: list[Path],
    data_free_kib: int,
    root_free_kib: int,
    output: Path,
) -> dict[str, object]:
    """Build a no-clobber draft for canonical terminal receipt publication."""

    root = repository.resolve()
    prefix = expected_prefix.resolve()
    if prefix != (root / ".venv-lerobot").resolve():
        raise ContractError("blocked receipt must name the unique .venv-lerobot prefix")
    dependency_payload = json.loads(dependency_evidence.read_text(encoding="utf-8"))
    if (
        dependency_payload.get("schema_version")
        != "lerobot-dependency-security-evidence.v1"
        or dependency_payload.get("status") != "blocked"
        or dependency_payload.get("environment_creation_allowed") is not False
    ):
        raise ContractError("dependency evidence does not prove a hard security blocker")

    evidence_entries = _evidence_entries(root, supporting_evidence)

    bootstrap_python = Path("/usr/bin/python3.12").resolve()
    payload = {
        "schema_version": "lerobot-smoke-receipt.v1",
        "receipt_id": None,
        "created_at_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "status": "blocked",
        "passed": None,
        "failure_stage": "dependency_security_audit",
        "reason_code": "dependency_security",
        "non_acceptance": True,
        "fallback_allowed": False,
        "backend_selected": None,
        "lock_classification": "development-blocked",
        "lerobot": {
            "tag": "v0.6.1",
            "commit": LEROBOT_COMMIT,
        },
        "environment": {
            "expected_prefix": str(prefix),
            "prefix_exists": prefix.exists(),
            "creation_attempted": False,
            "sync_attempted": False,
            "smoke_attempted": False,
        },
        "bootstrap_python": {
            "contract_path": "/usr/bin/python3.12",
            "realpath": str(bootstrap_python),
            "sha256": sha256_file(bootstrap_python),
        },
        "resources": {
            "phase": "initial",
            "data_free_kib": data_free_kib,
            "data_minimum_kib": 20 * 1024**2,
            "root_free_kib": root_free_kib,
            "root_minimum_kib": 3 * 1024**2,
        },
        "dependency_security_evidence": {
            "path": dependency_evidence.resolve().relative_to(root).as_posix(),
            "sha256": sha256_file(dependency_evidence),
            "size_bytes": dependency_evidence.stat().st_size,
            "issues": dependency_payload["issues"],
        },
        "source_lineage": {
            "complete": False,
            "source_input_manifest_id": None,
            "source_commit": None,
            "reason": "terminal blocker occurred before a formal clean source snapshot",
        },
        "evidence": evidence_entries,
    }
    with output.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.write("\n")
    return payload


def build_preflight_blocked_receipt(
    *,
    repository: Path,
    expected_prefix: Path,
    failure_stage: str,
    reason_code: str,
    data_free_kib: int,
    root_free_kib: int,
    supporting_evidence: list[Path],
    output: Path,
) -> dict[str, object]:
    """Build a terminal blocked draft when preflight cannot reach dependency audit."""

    allowed_reasons = {
        "df_unreadable",
        "insufficient_data_space",
        "insufficient_root_space",
        "directory_not_ignored",
        "dependency_input_missing",
        "dependency_audit_incomplete",
        "resolver_incomplete_or_indeterminate",
        "security_protocol_revision_required",
    }
    if reason_code not in allowed_reasons:
        raise ContractError(f"unsupported preflight blocker: {reason_code}")
    if not re.fullmatch(r"[a-z][a-z0-9_-]*", failure_stage):
        raise ContractError("invalid preflight failure stage")
    root = repository.resolve()
    prefix = expected_prefix.resolve()
    if prefix != (root / ".venv-lerobot").resolve():
        raise ContractError("blocked receipt must name the unique .venv-lerobot prefix")
    bootstrap_python = Path("/usr/bin/python3.12").resolve()
    payload = {
        "schema_version": "lerobot-smoke-receipt.v1",
        "receipt_id": None,
        "created_at_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "status": "blocked",
        "passed": None,
        "failure_stage": failure_stage,
        "reason_code": reason_code,
        "non_acceptance": True,
        "fallback_allowed": False,
        "backend_selected": None,
        "lock_classification": "not_admitted",
        "lerobot": {"tag": "v0.6.1", "commit": LEROBOT_COMMIT},
        "environment": {
            "expected_prefix": str(prefix),
            "prefix_exists": prefix.exists(),
            "creation_attempted": False,
            "sync_attempted": False,
            "smoke_attempted": False,
        },
        "bootstrap_python": {
            "contract_path": "/usr/bin/python3.12",
            "realpath": str(bootstrap_python),
            "sha256": sha256_file(bootstrap_python),
        },
        "resources": {
            "phase": "initial",
            "data_free_kib": data_free_kib,
            "data_minimum_kib": 20 * 1024**2,
            "root_free_kib": root_free_kib,
            "root_minimum_kib": 3 * 1024**2,
        },
        "dependency_security_evidence": None,
        "source_lineage": {
            "complete": False,
            "source_input_manifest_id": None,
            "source_commit": None,
            "reason": "preflight blocked before a formal clean source snapshot",
        },
        "evidence": _evidence_entries(root, supporting_evidence),
    }
    with output.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.write("\n")
    return payload


def reconcile_cuda_attempts(
    attempts: list[dict[str, object]],
) -> dict[str, object]:
    """Validate the immutable 4→2→1 ladder and decide its next state."""

    expected_batches = [batch for batch, _ in CUDA_LADDER]
    observed_batches = [attempt.get("microbatch") for attempt in attempts]
    if observed_batches != expected_batches[: len(observed_batches)]:
        raise ContractError("CUDA attempts must follow the exact 4, 2, 1 ladder")
    if len(attempts) > len(CUDA_LADDER):
        raise ContractError("CUDA attempts must follow the exact 4, 2, 1 ladder")

    for index, attempt in enumerate(attempts):
        if attempt.get("evidence_complete") is not True:
            return {
                "status": "blocked",
                "passed": None,
                "failure_class": "incomplete_evidence",
            }
        result = attempt.get("result")
        if result == "passed":
            batch, accumulation = CUDA_LADDER[index]
            return {
                "status": "passed",
                "passed": True,
                "selected_microbatch": batch,
                "gradient_accumulation_steps": accumulation,
                "effective_batch": 4,
            }
        if result == "compatibility_failed":
            failure_class = attempt.get("failure_class")
            if failure_class not in COMPATIBILITY_FAILURE_ALLOWLIST:
                return {
                    "status": "blocked",
                    "passed": None,
                    "failure_class": "unknown_failure",
                }
            return {
                "status": "failed",
                "passed": False,
                "failure_class": failure_class,
            }
        if result != "oom":
            return {
                "status": "blocked",
                "passed": None,
                "failure_class": "unknown_failure",
            }

    if len(attempts) == len(CUDA_LADDER):
        return {
            "status": "failed",
            "passed": False,
            "failure_class": "cuda_oom_batch1",
        }
    next_batch, next_accumulation = CUDA_LADDER[len(attempts)]
    return {
        "status": "continue",
        "passed": None,
        "next_microbatch": next_batch,
        "next_accumulation_steps": next_accumulation,
    }


def _argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    audit = subparsers.add_parser(
        "audit-lock", help="validate the lock and publish its security gate evidence"
    )
    audit.add_argument("--requirements", type=Path, required=True)
    audit.add_argument("--lock", type=Path, required=True)
    audit.add_argument("--output", type=Path, required=True)

    blocked = subparsers.add_parser(
        "blocked-receipt-draft",
        help="build a dependency-security blocked receipt for canonical publication",
    )
    blocked.add_argument("--repository", type=Path, required=True)
    blocked.add_argument("--expected-prefix", type=Path, required=True)
    blocked.add_argument("--dependency-evidence", type=Path, required=True)
    blocked.add_argument("--supporting-evidence", type=Path, action="append", default=[])
    blocked.add_argument("--data-free-kib", type=int, required=True)
    blocked.add_argument("--root-free-kib", type=int, required=True)
    blocked.add_argument("--output", type=Path, required=True)

    preflight = subparsers.add_parser(
        "preflight-blocked-receipt-draft",
        help="build a resource or ignore blocked receipt for canonical publication",
    )
    preflight.add_argument("--repository", type=Path, required=True)
    preflight.add_argument("--expected-prefix", type=Path, required=True)
    preflight.add_argument("--failure-stage", required=True)
    preflight.add_argument("--reason-code", required=True)
    preflight.add_argument("--data-free-kib", type=int, required=True)
    preflight.add_argument("--root-free-kib", type=int, required=True)
    preflight.add_argument("--supporting-evidence", type=Path, action="append", default=[])
    preflight.add_argument("--output", type=Path, required=True)
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = _argument_parser().parse_args(argv)
    try:
        if arguments.command == "audit-lock":
            payload = audit_dependency_lock(
                requirements=arguments.requirements,
                lock=arguments.lock,
                output=arguments.output,
            )
            return 3 if payload["status"] == "blocked" else 0
        if arguments.command == "blocked-receipt-draft":
            build_dependency_blocked_receipt(
                repository=arguments.repository,
                expected_prefix=arguments.expected_prefix,
                dependency_evidence=arguments.dependency_evidence,
                supporting_evidence=arguments.supporting_evidence,
                data_free_kib=arguments.data_free_kib,
                root_free_kib=arguments.root_free_kib,
                output=arguments.output,
            )
            return 0
        if arguments.command == "preflight-blocked-receipt-draft":
            build_preflight_blocked_receipt(
                repository=arguments.repository,
                expected_prefix=arguments.expected_prefix,
                failure_stage=arguments.failure_stage,
                reason_code=arguments.reason_code,
                data_free_kib=arguments.data_free_kib,
                root_free_kib=arguments.root_free_kib,
                supporting_evidence=arguments.supporting_evidence,
                output=arguments.output,
            )
            return 0
    except (ContractError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"LeRobot environment verification failed closed: {exc}", file=sys.stderr)
        return 2
    raise AssertionError(f"unhandled command: {arguments.command}")


if __name__ == "__main__":
    raise SystemExit(main())
